---
# tasks file for ansible-weblogic-server


- name: Update all packages
  yum: name=* state=latest

- name: Add groups 
  group:
    gid: "{{ item.gid }}"
    name: "{{ item.name }}"
    state: present
  with_items:
    - {gid: '501', name: 'oinstall'}

- name: Add user
  user:
    name: oracle
    uid: 500
    group: oinstall
    password: MDhjYWNkMzQ1NTA1MmZlN2Y2MGNiZTYz

- name: adjust selinux on server
  selinux:
    policy: target
    state: permissive

- name: disable firewalld on server
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: execute sysctl
  command: /sbin/sysctl -p

- name: Install required packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ packages_required }}"

- name: Restart server
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0

- name: wait for server {{ ansible_ssh_host | default(inventory_hostname) }} to come back online
  wait_for:
    port: 2829
    delay: 60
    search_regex: OpenSSH
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  connection: local

- name: create directory /u01/app/oracle/software/FMW/12.2.1.3.0/FM_Infra_12.2.1.3
  file:
    path: /u01/app/oracle/software/FMW/12.2.1.3.0/{{ item }}
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755
    recurse: yes
  with_items:
    - JDK
    - FM_Infra_12.2.1.3

- name: create directory /u01/app/oracle/procuct
  file:
    path: /u01/app/oracle/product/{{ item }}
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755
    recurse: yes
  with_items:
    - JAVA
    - FMW

- name: add a new string at the end of the file
  lineinfile:
    dest: /home/oracle/.bash_profile
    regexp: ''
    insertafter: EOF
    line: 'umask 027'

- name: Test if libXm.so.4 exist
  stat: path=/usr/lib64/libXm.so.4.0.4
  register: if.libXm.exist
  
- name: make link if libXm.so.4 exist
  file:
    src: /usr/lib64/libXm.so.4.0.4
    dest: /usr/lib64/libXm.so.3
    owner: root
    group: root
    state: link
  when: if.libXm.exist == True

- name: Copy JDK in folder
  copy:
    src=jdk-8u144-linux-x64.tar.gz
    dest=/u01/app/oracle/software/FMW/12.2.1.3.0/JDK/jdk-8u144-linux-x64.tar.gz
